# Sample TOML file for Regex-LE testing
# Test patterns: /^\[(.+)\]$/gm, /(\w+)\s*=\s*"([^"]+)"/g

[application]
name = "MyApplication"
version = "1.0.0"
port = 8080
debug = true

[database]
host = "localhost"
port = 5432
name = "mydb"
user = "admin"
password = "secretpass123"
url = "postgresql://admin:secretpass123@localhost:5432/mydb"

[api]
url = "https://api.example.com/v1"
key = "sk_live_abcd1234efgh5678"
timeout = 30000

[paths]
static = "./static"
assets = "/assets/images"
data = "../data/records.json"
logs = "/var/log/app.log"

[aws]
region = "us-east-1"
access_key_id = "AKIAIOSFODNN7EXAMPLE"
secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

[features]
auth = true
analytics = false
logging = true

[metadata]
created = "2025-01-27T10:00:00Z"
tags = ["test", "sample", "toml"]

